name: build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]         # v1.0.0 같은 태그 푸시 시 릴리즈
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 태그 릴리즈에 필요
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -U -DskipTests clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: LobbySelector-${{ github.sha }}
          path: target/LobbySelector-*.jar
          if-no-files-found: error

      # 태그로 푸시하면 자동 릴리즈(옵션)
      - name: Prepare release asset
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p dist
          cp target/LobbySelector-*.jar "dist/LobbySelector-${GITHUB_REF_NAME}.jar"

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/LobbySelector-${{ github.ref_name }}.jar
          generate_release_notes: true
