# ServerGUI 설정 (Paper 1.21.1, Java 21)
menu-title: "&6서버 선택"
menu-size: 9

# Velocity의 [servers] 키와 id가 '정확히 동일'해야 이동됩니다.
servers:
  - id: "pix121"
    name: "&b픽셀몬 1.21.1"
    material: "NETHER_STAR"
    slot: 3
    lore:
      - "&7NeoForge 1.21.1"
      - "&e클릭하면 이동"
  - id: "pixelmon"
    name: "&a픽셀몬 1.16.5"
    material: "DIAMOND_PICKAXE"
    slot: 5
    lore:
      - "&71.16.5 Forge/CatServer"
      - "&e클릭하면 이동"

npc:
  linked-ids: []   # /서버 연동 으로 등록됩니다.
