name: ServerMenuBridge
version: '1.0.1'
main: gg.samlobby.bridge.ServerMenuBridgePlugin
api-version: '1.21'
authors: [ 'SamLobby' ]
softdepend: [Citizens]
commands:
  servermenu:
    description: Open server menu when looking at an NPC
    aliases: [ '서버메뉴' ]
    permission: servermenu.use
  samlobby:
    description: Admin commands (reload/open)
    permission: servermenu.admin
permissions:
  servermenu.use:
    default: true
  servermenu.admin:
    default: op
